FROM python:3.8-alpine
COPY . /app
WORKDIR /Users/adityabanerjee/Desktop/Udemy-Complete AIML Bootcamp/ML Ops/Docker
RUN pip install -r /Users/adityabanerjee/Desktop/Udemy-Complete AIML Bootcamp/ML Ops/Docker/requirements.txt
CMD flask run